'This script has been generated by PowerPCB's VB Script Wizard on 12/5/2014 11:38:45 AM
'It will create reports in Text format.
'For better look, turn off 'Word Wrap' item in the Edit menu of Notepad and use Courier or any other fixed width font.
'You can use the following code as a skeleton for your own VB scripts


Sub Main
	'Make report file name from current schematic file name
	fname = ActiveDocument
	If fname = "" Then
		fname = "Untitled"
		report = DefaultFilePath & "\default.rep"
	Else
		nm = Left(fname, Len( fname) - 4)
		report = DefaultFilePath & "\" & nm & ".rep"
	End If
	Open report For Output As #1
	'Output report header

	Print #1, "Report Origin = (0.0, 0.0)"
	Print #1, "Units used = ""mil"""
	Print #1, """Name"",""layer"",""CenterX"",""CenterY"",""Orientation"""
	Print #1

	StatusBarText = "Generating report..."
	
	For Each part In ActiveDocument.Components
		Print #1, """" & part.Name & """, """ & ActiveDocument.LayerName(part.layer) & """, """ & Format(part.CenterX(unit:=2), "0.000") & """, """ & Format(part.CenterY(unit:=2), "0.000") & """, """ & part.Orientation & """"
	Next part


	StatusBarText = ""
	Close #1
	'Do not forget quotes for file name!
	Shell "Notepad " & Chr(34) & report & Chr(34), 1
End Sub

