# environment
include ../../common/Makefile.include

# bsg_celerity_loopback variables
include ../Makefile.include

export BSG_OUT_DIR:=$(BSG_GATEWAY_DIR)/out

include $(BSG_FPGA_FIRMWARE_DIR)/common/$(BSG_GATEWAY_TARGET)/Makefile
